source $HOME/.dotfiles/config/vim/vimrc_plugins

" This comes first, because we have mappings that depend on leader
" With a map leader it's possible to do extra key combinations
" i.e: <leader>w saves the current file
let mapleader = ","

source $HOME/.dotfiles/config/vim/vimrc_plugins_settings
source $HOME/.dotfiles/config/vim/vimrc_settings
source $HOME/.dotfiles/config/vim/vimrc_mappings
source $HOME/.dotfiles/config/vim/vimrc_extended
